### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by vochicong**
Alternative docker implementation to #323 and #779, both seem not merged into master .

### CODE REVIEW

**Comment by vochicong** [comment]
FYI, I'm also trying to use Snorkel with Google Cloud Datalab.
https://github.com/vochicong/datalab-nlp

**Comment by riyadparvez** [comment]
What's the status of this PR?

**Comment by vochicong** [comment]
Reopened, since people show interests in #779.

**Comment by vochicong** [comment]
I don't remember changes in `.travis.yml`, and it is hard to resolve conflicts in that file now.
I will try this again when I need Snorkel.

**Pull request closed without merging**
