### PR TITLE
Refactor and restructure end_model/ to classification/

### PR DESCRIPTION
**Pull request by bhancock8**
This PR is mostly a refactor/restructuring of the `end_model` directory, which will now have the following structure:
```
classification/
	training/
		__init__.py
		loggers/
			…
		schedulers/
			…
		trainer.py
	models/
		classifier.py
		simple_classifier.py
		advanced/
			advanced_classifier.py
			task.py
			utils.py
	data.py
	scorer.py
	utils.py
```
- Along with the name changes of files, I replaced "Multitask" in MultitaskModel, MultitaskDataset, and MultitaskDataLoader with "Classification".
- Test directory has been updated to match
- Moved test_split_data() to its proper place in the test directory (it apparently didn't migrate out of model/ when it's corresponding method did)

**Test plan:**
All unit tests continue to pass after the refactor

### CODE REVIEW

**Comment by henryre** [comment]
where did snorkel/classification/training/trainer.py come from? and why advanced instead of multitask?

**Comment by bhancock8** [comment]
It was `snorkel/end_model/[a lot of things including trainer.py]`. Now it's broken down into `training/` and `models/`

Advanced instead of multitask because that more flexible model is the best model to use for a lot of different things, including many non-multitask ones. (e.g., none of the SuperGLUE models were multi-task, but many of them had unusual architectures that needed the more flexible model specification).

**Comment by henryre** [comment]
Ok so why is this diff SLOC +700 -180?

**Comment by bhancock8** [comment]
That's a great question. Answer: end_model/ wasn't fully deleted. Now that it is, the diff is SLOC +181 -182.

**Comment by bhancock8** [comment]
Replacing with #1216 (same commits but rebased on redux tip to avoid merge conflict with hot fix)

**Pull request closed without merging**
