### PR TITLE
Dockerfile for Snorkel containers

### PR DESCRIPTION
**Pull request by netj**
To ease user's setup for running notebooks with Snorkel and all its dependencies, based on [jupyter/datascience-notebook](https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook).

If user has Docker installed, they can open http://localhost:12345 after
this oneliner:

```
docker run -it -p12345:8888 --volume "$PWD":/work --rm hazyresearch/snorkel
```

Configuring your Docker to use our local registry mirror (`http://raiders6.stanford.edu:5000`) is a good idea as it has to download ~3GB from the cloud.

---

This is the production Dockerfile mentioned in #321.  The one for development could be done on top of this or separately.

@ajratner Let me know your username for https://hub.docker.com so I can add you to the hazyresearch org owners.

### CODE REVIEW

**Comment by ajratner** [comment]
This looks great!  I'll get an account set up on docker hub, and merge this
once new PR is merged- thanks Jaeho!

**Comment by ajratner** [comment]
@netj ping me when ready- no rush

**Comment by ajratner** [comment]
Hey @netj just FYI- am snoozing this PR, ping me here whenever I should review & merge!

**Comment by vochicong** [comment]
I've found that the docker image [hazyresearch/snorkel](https://hub.docker.com/r/hazyresearch/snorkel) is last updated a year ago.
Do you have any newer image?

**Pull request closed without merging**
