### PR TITLE
Actually add built-in length function for candidates

### PR DESCRIPTION
**Pull request by bhancock8**
Here's a cleaner PR on a separate branch. Merge this one instead and drop the other PR.

### CODE REVIEW

**Comment by henryre** [comment]
Looks good to me, but @ajratner has been in rare form today so maybe he can rip it to shreds. Will merge once Trav 😎 gives the go ahead

**Comment by ajratner** [comment]
LGTM :)  I just don't support wild and crazy vigilantes like @henryre who go submitting HUGE changes to the codebase without approval!!  Sad!

**Comment by bhancock8** [comment]
@ajratner You've nailed the tone. I hope this continues for four more years.

Also, what's protocol on PRs: once it's got the stamp of approval as this one does, who actually merges it into master--the submitter, the approver, anyone?

**Comment by henryre** [comment]
Me!

**Pull request merged**
