### PR TITLE
Adding entity_cids and entity_types to Sentence

### PR DESCRIPTION
**Pull request by ajratner**

### CODE REVIEW

**Comment by henryre** [comment]
LGTM!

**Comment by stephenbach** [comment]
Do CIDs need to be stored at the candidate level to handle cases such as compound entity mentions and to subsume ImplicitSpans?

**Comment by ajratner** [comment]
@stephenbach So I also submitted a PR for storing them at the candidate level a few days ago- this PR is just to enable tagging entities as part of the preprocessing stage.  I.e. I want to be able to run all the PubMed entity parsers without having to create (and thus pre-specify) a Candidate set.

Any suggestions of how to make this distinction clearer though are welcome?

**Comment by stephenbach** [comment]
Ah, perfect! Thanks for the clarification!

**Pull request merged**
