### PR TITLE
Small parser patch

### PR DESCRIPTION
**Pull request by henryre**
IDK why this was broken or what this is actually fixing.

### CODE REVIEW

**Comment by henryre** [comment]
Actually this looks like it's stemming from a merge issue in
* https://github.com/HazyResearch/snorkel/commit/10f23e6ca0742ba0ed05e6393db94bd515e4778d
* https://github.com/HazyResearch/snorkel/commit/35e714902e04c58118ce2445fbaef3ad7d138af4

@bhancock8 can you check this out and make the appropriate changes and/or rollback `parser.py` to `ab7b23`

**Comment by bhancock8** [comment]
Yep--your fix is exactly what was needed, and it makes sense. Looks like the `get` function being dropped was just a transcription error. The original line looked like this:

`parts['text'] = ''.join(t['originalText'] + t.get('after', '') if i < L - 1 else t['originalText'] for i,t in enumerate(block['tokens']))`

And after we worked out the bug in CoreNLP being caused by PTB characters, that extra "if" statement wasn't needed. This patch looks good to me.

**Comment by henryre** [comment]
Ok cool, can you run a diff on the rest of the file to make sure everything else was preserved?

**Comment by bhancock8** [comment]
Yep--diff looks good. That's everything.

**Pull request merged**
