### PR TITLE
New Website

### PR DESCRIPTION
**Pull request by paroma**
- Temporary redesign and restructure for Workshop
- Highlight Snorkel captures Augment, Slice, and Label
- Old links to Blogs, Papers, and Use Cases maintained
- Overview Image for SFs

### CODE REVIEW

**Comment by bhancock8** [comment]
Can use https://htmlpreview.github.io/ to preview the rendered page:
https://htmlpreview.github.io/?https://github.com/HazyResearch/snorkel/blob/b8019d38b56f6889b6b0891c78b91a153c82fa52/index.html

**Comment by bhancock8** [comment]
Nice! 1000x better. 

A few nits:
- blue bold means a link everywhere except for the first paragraph, and that's confusing.
- typo: massive multi-task learnings
- logos: I don't think MEMEX means anything to most people; maybe just the larger/cleaner DARPA logo?

**Comment by ajratner** [comment]
@paroma I'll look over tomorrow AM!

**Comment by paroma** [comment]
addressed https://github.com/HazyResearch/snorkel/pull/1130#issuecomment-503320897

**Comment by ajratner** [comment]
@paroma Going to do an editing pass now

**Comment by ajratner** [comment]
@paroma I did an editing pass.  I'm fine with this going live although I do think we should all (myself included since tired) do one or more editing passes over this still... it's important!!

A few quick additional items before going live though:
- The "More..." news items button doesn't appear to do anything?  Either implement or take out?  Or just have it be a link to bottom of page maybe?
- Can you put in the slicing picture from the slicing paper, so all three ops have pics?
- Also TODO: Copy the bulk of this (maybe everything before references, or at least the top bit) to README of `redux`

Thanks!

**Comment by paroma** [comment]
re: https://github.com/HazyResearch/snorkel/pull/1130#issuecomment-504636657
* None of the javascript works in the preview, but it worked for me when I deployed using Jekyll. I'll check once it goes live
* is there a slicing picture that matches the format of the other two? (@vincentschen)
* adding to README sounds good!

**Comment by vincentschen** [comment]
> * is there a slicing picture that matches the format of the other two? (@vincentschen)

Options:
architecture_blog_simple (2)

synthetics_overview

**Comment by vincentschen** [comment]
Another nit: 
* The subsections under "References" look like links, but don't link anywhere. ("Blogs and Tutorials", "Papers and Pre-Prints", "Snorkel Use Cases"

**Comment by paroma** [comment]
re: https://github.com/HazyResearch/snorkel/pull/1130#issuecomment-504693197
its a click to open and close , ill replace it with having top 5 and then a More... there. its not working in the preview since it doesn't run JavaScript

**Comment by ajratner** [comment]
@paroma the "More..." button still appears defunct?  Other than that LGTM

**Comment by paroma** [comment]
@ajratner is this after `Jekyll serve`? It works if I click on it (and changes blue > dark blue like other "links")

**Pull request merged**
