### PR TITLE
Partially fixes #582

### LINKED ISSUE #582: Array slicing breaks csr_AnnotationMatrix objects
I'd like to take a subset of candidate instances to train the generative model and then save those marginals for use in the discriminative model. 

I thought this could be done just taking a subset slice of the label matrix.  However, when I use  slice notation on a csr_AnnotationMatrix object to generate my model input, I run into errors when attempting to save the marginals later on in the program. For example:

```
L_train = labeler.load_matrix(session, split=0)
print L_train.get_candidate(session,0)
```
will correctly access and the mapped candidate object. 
However, if we take a slice of the label matrix, e.g., 
```
L_train_subset = L_train[0:n,...]
print L_train_subset.get_candidate(session,0)
```
the `get_candidate` function breaks with the following error
```
File "/home/user/code/dd-patient-notes/snorkel/snorkel/annotations.py", line 39, in get_candidate
    return session.query(Candidate).filter(Candidate.id == self.row_index[i]).one()
TypeError: 'NoneType' object has no attribute '__getitem__'
```
everything works otherwise in terms of training, just the mapping between candidate and row index seems to break.

### PR DESCRIPTION
**Pull request by ajratner**
I got this working for slices (e.g. `a:b`) but can't figure out how to handle / what subfunction of `csr_matrix` class handles slicing by array / list... have to pause on this for now, maybe is worth pulling in as is, or someone else can pick up from where I left off?

### CODE REVIEW

**Comment by ajratner** [comment]
Hey @jason-fries or @stephenbach thoughts on merging this into master?  The issue we can only do slices like `X[a:b]` but not `X[s]` where `s` is an array... but might as well put in the former capability for now (won't negatively change anything)?

**Comment by jason-fries** [comment]
I like the flexibility of Numpy's slice notation. I put some thoughts earlier on this issue at https://github.com/HazyResearch/snorkel/issues/582#issuecomment-311566563

I'd vote to keep things as it, but i don't feel that strongly.

**Comment by ajratner** [comment]
Sorry I could have been clearer: Numpy's standard slice notation is already in place.  The only problem (without this PR) is that using slicing in any way breaks the index that allows you to use the e.g. `get_candidate` or `get_key` helper methods.

This PR just extends the set of slice operations where the index will not be broken (to include all `a:b`-type ones).  So it's a minimal but purely additive fix

Also, as of latest changes (on `new_intro` branch), the learning / grid search methods (basically everything but the `classifier.error_analysis` method) will work without this index anyways (i.e. #569 has been fixed)

**Comment by stephenbach** [comment]
LGTM!

**Pull request merged**
