### PR TITLE
Switch spacy installation to conda from pip

### PR DESCRIPTION
**Pull request by dhimmel**
Hopefully this will reduce the 550 second [install time](https://travis-ci.org/HazyResearch/snorkel/jobs/374664220#L1708) of the conda environment. It [looks like](https://travis-ci.org/HazyResearch/snorkel/jobs/374670307#L566) it reduces install time to 330 seconds.

Refs https://github.com/HazyResearch/snorkel/pull/876
Closes https://github.com/HazyResearch/snorkel/issues/724 (which actually has already been addressed).

### CODE REVIEW

**Comment by dhimmel** [comment]
See build to confirm that spacy 2 is being installed:

+ https://travis-ci.org/HazyResearch/snorkel/jobs/374670307#L742
+ https://travis-ci.org/HazyResearch/snorkel/jobs/374670308#L730

**Comment by dhimmel** [comment]
I narrowed down the issue. The following cell is going to take about 16 minutes to run on my device (it's about 10 seconds for every percentage point):

screenshot from 2018-05-03 20-30-18

One solution which is not ideal is [to use](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) `travis_wait`. However, we don't want build times to slow down, so it may be worth looking into why this command is now slower and think about whether we should address that.

**Comment by stephenbach** [comment]
One other thing: it should only process 500 docs on travis, based on the variable set in the first cell. Perhaps it needs to be lowered further? But annoying if spacy 2 is actually the issue.

**Comment by dhimmel** [comment]
Downgrading to version 1 of spacy fixed the slowness issue (see https://github.com/HazyResearch/snorkel/pull/924/commits/c697d24dbea6f453820683cd50ded05b84e35f21). This PR is still productive because it switches the spacy installation to use conda from pip, which prevent installation errors on my system and is faster. So we should consider merging... if so I'd rename to "Switch spacy installation to conda from pip" and use a squash merge so we don't merge in the intermediate commits.

Alternatively, we could look a bit more into speeding up spacy 2. Possibly related to https://github.com/explosion/spaCy/issues/1508

**Pull request merged**
