### PR TITLE
Adding classes to support Document objects as Candidates

### PR DESCRIPTION
**Pull request by chaturv3di**
Addressing issues #1055 and #1062.

### CODE REVIEW

**Comment by chaturv3di** [comment]
I checked the logs and the error that's reported is

`The command "conda env create --quiet --file=environment.yml" failed and exited with 1 during .`

Is there anything I can do to fix this?

**Comment by bhancock8** [comment]
It looks like the failed test was conda's fault; the connection broke while it was trying to pull a package. I reran it and the test passed just fine. Thanks for the contribution!

**Comment by YipingNUS** [comment]
Thanks for the solution. Worked for me for document classification. Seems like you forgot to add the import lines in \_\_init\_\_. It will raise DocRNN not found error (I installed by ```pip install .``` following the instructions in README). 

rnn/\_\_init\_\_.py:

```
from .doc_rnn import DocRNN
```

tensorflow/\_\_init\_\_.py:

```
from .rnn import reRNN, TagRNN, TextRNN, **DocRNN**
```

**Comment by chaturv3di** [comment]
Oops! Thanks a lot for pointing this out. I'll fix this asap.

**Pull request merged**
