### PR TITLE
Rename learned LabelModel params

### PR DESCRIPTION
**Pull request by paroma**
* Rename LabelModel params from accuracies to weights
* Change LF summary table field from `Learned Acc.` to `Learned Weight`
* Increase delta for parameter for one test

__Test Plan__
* Change tests according to renaming scheme

### CODE REVIEW

**Comment by henryre** [comment]
@paroma ready for review?

**Comment by paroma** [comment]
ready!

**Comment by henryre** [comment]
any corresponding changes needed in tutorials @paroma ?

**Comment by paroma** [comment]
no changes in tutorials required

**Pull request merged**
