### PR TITLE
Remove future imports

### PR DESCRIPTION
**Pull request by henryre**
Unused and can break compatibility

### CODE REVIEW

**Comment by ajratner** [comment]
I think this might be for Python 3 compatibility?  See https://github.com/HazyResearch/snorkel/pull/702/files#diff-398030fcfc468a8ee24a7f8c21053a96L22

**Comment by henryre** [comment]
Well they're both unused, and sometimes conda messes up the six/future install. I vote we just remove.

**Comment by ajratner** [comment]
There's one usage in `db_helpers.py`

**Comment by henryre** [comment]
It's not using this import (just the `dict` method), so that call breaks in Python 3. I have a few more Python 3 fixes, so let me close this for another PR.

**Pull request closed without merging**
